services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: emailbreach
    container_name: emailbreach
    environment:
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}

  backend-arm64:
      build:
        context: .
        dockerfile: ./Dockerfile
        platform: linux/arm64
      image: emailbreach-arm64
      container_name: emailbreach-arm64
      environment:
        - RAPIDAPI_KEY=${RAPIDAPI_KEY}
        
  reverse-proxy:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: reverseproxy
    container_name: reverseproxy
    ports:
      - "80:80"
    depends_on:
      - backend
