version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: backend
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

