version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    environment:
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}

  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"      # expose nginx to cloudflare tunnel (awesome sauce)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
