services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: emailbreach
    environment:
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}

  reverse-proxy:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: reverseproxy
    ports:
      - "80:80"
    depends_on:
      - backend
