version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: backend
    volumes:
      - ./:/app
    ports:
      - "5000:5000"  # Exposes Flask app
    environment:
      - FLASK_ENV=development
    image: ghcr.io/ajprogramming123/emailbreach-backend:v1.1

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    ports:
      - "80:80"  # Expose nginx on default HTTP
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Mount your custom config
    image: ghcr.io/ajprogramming123/emailbreach-frontend:v1.1
