services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: emailbreach
    container_name: emailbreach
    environment:
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}

  backend-arm32:
    platform: linux/arm/v7  
    build:
      context: .
      dockerfile: ./Dockerfile
    image: emailbreach-arm32
    container_name: emailbreach-arm32
    environment:
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}
        
  reverse-proxy:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: reverseproxy
    container_name: reverseproxy
    ports:
      - "80:80"
    depends_on:
      - backend
