name: ARM64 ---- Docker image push!! [flask app setup]

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New image tag to apply (e.g., v1.2)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ajprogramming123
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push ARM64 backend image
        run: |
          docker buildx build \
            --platform linux/arm/v7 \
            --tag ghcr.io/ajprogramming123/emailbreach-arm64:${{ github.event.inputs.new_version }} \
            --push .
