name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag (e.g., v1.2 or latest)'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ajprogramming123
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Create .env file with secrets
        run: echo "APIKEY=${{ secrets.APIKEY }}" > .env

      - name: Build images with Docker Compose
        run: docker compose build

      - name: Tag images with input version
        run: |
          docker tag ghcr.io/ajprogramming123/emailbreach-backend:latest ghcr.io/ajprogramming123/emailbreach-backend:${{ github.event.inputs.tag }}
          docker tag ghcr.io/ajprogramming123/emailbreach-frontend:latest ghcr.io/ajprogramming123/emailbreach-frontend:${{ github.event.inputs.tag }}

      - name: Push images to GitHub Container Registry
        run: docker compose push
