name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build images with Docker Compose
        run: docker compose build

      - name: Tag backend image with version
        run: |
          docker tag ghcr.io/ajprogramming123/emailbreach-backend:v1.1 ghcr.io/ajprogramming123/emailbreach-backend:${{ github.event.inputs.version }}

      - name: Tag frontend image with version
        run: |
          docker tag ghcr.io/ajprogramming123/emailbreach-frontend:v1.1 ghcr.io/ajprogramming123/emailbreach-frontend:${{ github.event.inputs.version }}

      - name: Push backend image with version tag
        run: docker push ghcr.io/ajprogramming123/emailbreach-backend:${{ github.event.inputs.version }}

      - name: Push frontend image with version tag
        run: docker push ghcr.io/ajprogramming123/emailbreach-frontend:${{ github.event.inputs.version }}
