name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      old_version:
        description: 'Old image tag (e.g., v1.1)'
        required: true
      new_version:
        description: 'New image tag to apply (e.g., v1.2)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ajprogramming123
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build images with docker-compose
        run: |
          docker compose build


      
      - name: Retag backend image
        run: |
          docker tag ghcr.io/ajprogramming123/emailbreach:${{ github.event.inputs.old_version }} ghcr.io/ajprogramming123/emailbreach:${{ github.event.inputs.new_version }}

      - name: Push new backend tag
        run: docker push ghcr.io/ajprogramming123/emailbreach:${{ github.event.inputs.new_version }}

      - name: Push new nginx (reverse proxy) tag
        run: docker push ghcr.io/ajprogramming123/emailbreach-reverseproxy:${{ github.event.inputs.new_version }}
