name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ajprogramming123
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Create .env file
        run: echo "APIKEY=${{ secrets.APIKEY }}" > .env

      - name: Build and tag backend image
        run: |
          docker build \
            --build-arg APIKEY=${{ secrets.APIKEY }} \
            -t ghcr.io/ajprogramming123/emailbreach-backend:1.1 ./src
#Change the name here (on top)

      - name: Build and tag frontend image
        run: |
          docker build \
            -t ghcr.io/ajprogramming123/emailbreach-frontend:1.1 ./frontend
#Change the name here (on top)

#---pushing the image---#
      - name: Push backend image
        run: docker push ghcr.io/ajprogramming123/emailbreach-backend:1.1

      - name: Push frontend image
        run: docker push ghcr.io/ajprogramming123/emailbreach-frontend:1.1
